Support  WILL message
reaktivity/nukleus-mqtt.spec pull request #45
Opened 2020-09-09 23:57 UTC by dknoma

2020-09-10 00:02 UTC, dknoma commented
Example of JSON metadata
```
{
    “clientId”: “client”,
    “subscriptions”: [
        {
            “topic”: “sensors/1”,
            “identifier”: 1,
            “flags”: 0
        }
    ],
    “will”: {
        “topic”: “$SYS/session/client”,
        “qos”: 0,
        “retained”: false
        “properties”: {
            “delayInterval”: 3000
        },
        “payload”: “payload”,
    }
}

```

2020-09-17 20:38 UTC, dknoma commented
Example of binary metadata format in .idl
```
        struct MqttSubscription
        {
            string16 topic;
            varbyteuint32 identifier;
            uint8 flags;
        }

        struct MqttSubscriptions
        {
            MqttSubscription[] subscriptions;
        }

        struct MqttWill
        {
            string16 topic;
            uint8 qos;
            uint8 retained;
            MqttProperties properties;
            octets payload;
        }

        list<uint32, uint32> MqttSession
        {
            required uint64 expiresAt;
            required MqttSubscriptions subscriptions;
            MqttWill will;
        }
```

2020-10-17 04:51 UTC, jfallows requested changes

2020-10-17 04:51 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/mqtt/streams/publish.session.data/client.rpt
> +                              .topic("$SYS/clients/client/#")
Perhaps we can use a `clientId` other than `client` so this reads a little more easily, such as `one`, giving `$SYS/clients/one/#`?

2020-10-17 04:51 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/mqtt/streams/publish.session.data/server.rpt
> +write "{\"expiresAt\":10}"
Can we use single quotes around the outside to avoid having to escape the double quotes inside?
That would be more readable.

2020-10-17 04:51 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/mqtt/streams/publish.session.data/server.rpt
> +read "payload"
Let's use a more descriptive `WILL` message to help describe the scenario, such as `"client one session expired"`.
How is the metadata stored for the `will topic` where this message will eventually be published after the session expires?
What about user properties for the `will message`?

2020-10-19 19:12 UTC, jfallows approved these changes

2020-10-19 19:14 UTC, merged